### ISSUE TITLE
Build issues on macOS Mojave

### ISSUE THREAD

**Issue by boonier** [PaulBatchelor/ChuckSound#1] opened 2020-06-16 09:02 UTC
Hi Paul

Hope you can help, I'm having some build issues on macOS. I suspect given the sdks and libraries have moved on a fair bit since 2015, it was going to be a problem :)

When I run `make osx` I get this:

```
clang++ -mmacosx-version-min=10.5 -D__MACOSX_CORE__ -Ichuck/include/ -arch x86_64 -fPIC -I/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Headers/ -DBUILD_OSX -O3 -c -o ugen_csound.o ugen_csound.cpp
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from ugen_csound.cpp:1:
In file included from chuck/include/chuck_type.h:38:
chuck/include/chuck_oo.h:38:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make: *** [ugen_csound.o] Error 1
```

Any ideas on what I should do? `warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead' on the command line to use the libc++ standard library instead` this looks the likely culprit, but I'm not too sure where this needs to be change..

also when you say Csound has to be compiled for this to work, does the compile process leave some side-effects that ChuckSound needs? It's not enough to have installed Csound?

thanks

**Comment by PaulBatchelor** [comment] 2020-06-16 20:18
Huh. That's a weird error to get. My best guess is follow the errors advice and add "-stdlib=libc++" to FLAGS in makefile.osx and see if that fixes things:
https://github.com/PaulBatchelor/ChuckSound/blob/master/makefile.osx

> also when you say Csound has to be compiled for this to work, does the compile process leave some side-effects that ChuckSound needs? It's not enough to have installed Csound?

Knowing me then, I think I used the term "compile" pretty casually here, as I was so used to compiling and installing Csound from source at the time of writing. Specifically, what is needed are the libraries and frameworks needed to use the Csound API. You may be fine with regular installation if those are included already.

**Comment by boonier** [comment] 2020-06-16 21:24
Thanks for getting back. I updated the makefile.osx to 
```
ARCHS?=x86_64
ARCHOPTS=$(addprefix -arch ,$(ARCHS))
CSFRAMEWORK_HPATH=/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Headers/
CSFRAMEWORK_LDPATH=/Library/Frameworks/CsoundLib64.framework/Versions/6.0/
CSFRAMEWORK_FPATH=/Library/Frameworks/

FLAGS+=-mmacosx-version-min=10.9 -D__MACOSX_CORE__ -I$(CK_SRC_PATH) $(ARCHOPTS) -fPIC -I$(CSFRAMEWORK_HPATH) -DBUILD_OSX -stdlib=libc++
LDFLAGS+= -F $(CSFRAMEWORK_FPATH) -L $(CSFRAMEWORK_LDPATH)
LDFLAGS+= -DUSEDOUBLE  -L/usr/local/lib -framework CsoundLib64 -mmacosx-version-min=10.9 -shared -lstdc++ $(addprefix -framework ,$(FRAMEWORKS)) $(ARCHOPTS)

LD=clang++
CXX=clang++
```
note I bumped the min version to 10.9 and added the suggested flag, now I have a different error:

```
clang++ -F /Library/Frameworks/ -L /Library/Frameworks/CsoundLib64.framework/Versions/6.0/ -DUSEDOUBLE  -L/usr/local/lib -framework CsoundLib64 -mmacosx-version-min=10.9 -shared -lstdc++  -arch x86_64 -o Csound.chug ugen_csound.o
Undefined symbols for architecture x86_64:
  "CsoundPerformanceThread::InputMessage(char const*)", referenced from:
      _csound_inputMessage in ugen_csound.o
  "CsoundPerformanceThread::CsoundPerformanceThread(CSOUND_*)", referenced from:
      _csound_compile_csd in ugen_csound.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Csound.chug] Error 1
```
Not sure, is this progress... is it looking for 32 bit libraries to compile for 64 bit?

**Comment by PaulBatchelor** [comment] 2020-06-16 21:47
Huh. If I were guess, I would say it can't find the libraries. Can you check and see if something resembling "libcsnd*" is in `/usr/local/lib`? See what pops up for:

```
ls /usr/local/lib/libcsnd*
```

FWIW, I was able to get this to compile on Mojave with the tweaks. My system is a little janky at the moment, but I *think* I was using the libraries + frameworks from the latest OSX installer (just installed minutes ago). Installing + running, however, is still broken and some of the chuck-related things may need to be updated.

**Comment by PaulBatchelor** [comment] 2020-06-16 22:10
@boonier So I pushed some changes in ce3c52afe7de4b355cbbf28bbf615f8bf1ccc851 that should get ChuckSound to build + install on OSX Mojave. Could you confirm that it builds okay on your end?

While I can confirm that the plugin is indeed detected by ChucK version 1.4.0.1, the program does seem to crash for whatever reason.

**Comment by boonier** [comment] 2020-06-16 22:22
@PaulBatchelor great! thanks for looking into it. will check out now

**Comment by PaulBatchelor** [comment] 2020-06-16 22:31
@boonier please report back on if things compile or not.

full disclosure, this is a dead project I do not plan on reviving. unless you or someone you know wants to take over maintaining it, it may not be worth sinking your teeth into.

ChuckSound will start up, but it will segfault and crash somewhere. I've been digging around and looking at some [reference code](https://github.com/csound/csoundAPI_examples/blob/master/cpp/csPerfThreadExample.cpp) to try see if there have been any changes to the Csound C++ API (it seems there have), but I can't seem to get it to stop crashing.

One thing that I am doing with ChuckSound that is strange and atypical is that I am hijacking the csound audio callback to render buffers inside of the ChucK ugen rather than inside of the hardware. This requires some way-too-clever hacks on the C++ end as well in the main Csound CSD. If there are problems, I suspect it may be related to this. Since it exists at the API layer, it could be possible that this behavior that I relied on has been changed or disabled since I last used it. Those bits seem to change around more than the other internals like Opcodes.

**Comment by boonier** [comment] 2020-06-17 07:35
@PaulBatchelor Still getting this error

```
clang++ -o Csound.chug ugen_csound.o -F /Library/Frameworks/ -L /Library/Frameworks/CsoundLib64.framework/Versions/6.0/ -DUSEDOUBLE  -L/usr/local/lib -lcsnd6 -framework CsoundLib64 -mmacosx-version-min=10.9 -shared -lstdc++  -arch x86_64
ld: library not found for -lcsnd6
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Csound.chug] Error 1
```
I think it must be that missing lib on my machine...assuming you have the latest source pulled for Csound, meaning, you'd have that library? Fun and games :)

Have you moved on from ChucK/Csound or both since? I was keen to get at the tasty Csound ugens (fft and granular mainly), as I'm pretty new to ChucK, but if Csound is a bit redundant now that ChucK has come along, then I won't sweat it too much! Pity my C/C++ chops aren't the best, so it would take me a while to get my head around what would need to be done. I do agree that the fundamental changes are in Csound's api, having read a few similar bits around the forums.

cheers

**Comment by PaulBatchelor** [comment] 2020-06-17 14:04
Huh. Well, I really don't know why it can't find csnd6. It may have to something you build from source. As I said, my OSX setup is a bit of a mess. It might have Csound components built from source, it might also have bits from the Csound installer.

FWIW, Csound should be a reasonably painless thing to build from source. It uses CMake these days, which takes care of most of the dependency management. Plus, you can turn on some cool features that don't installed in the default Csound OSX build.

> Have you moved on from ChucK/Csound or both since?

Yes, and yes. Csound is a bit like the cool aunt who I never get to visit enough. I don't use Csound these days because I build my own tools. Things like [sporth](https://github.com/paulbatchelor/sporth) and [soundpipe](https://github.com/paulbatchelor/soundpipe) suit my compositional needs in a much more lightweight and portable way. It doesn't have as many shiny things as Csound, but I've gotten pretty far with them. IMO, they are also much more fun to hack on an embed into other projects, which is something that matters a great deal (btw, my [chorth](https://pbat.ch/proj/chorth.html) plugin still works on OSX).

> Csound is a bit redundant now that ChucK has come along since 2015

No. No it is not. Not even close. Even with all the [chugins](https://github.com/ccrma/chugins), the ChucK sound palette is still incredibly limited compared to those provided by Csound. Even if it did have the same number of ugens as Csound, the language used to construct synthesizers in a semi-modular fashion in ChucK is quite limited compared to Csound's orchestra syntax.

I also have no reason to believe that they've fixed this [critical memory leak](https://github.com/ccrma/chuck/issues/49#issuecomment-186478107) I found 4 years ago. This particular memory leak is pretty bad, because it effects virtually all live coding efforts in ChucK. It was definitely one of those show-stopper moments for me.

Anyways, if I could be bold enough to impart any wisdom it would be this: Learn Csound. It will change your life, and help you grow as an artist. It will grow with you too! Supplementary wisdom to this would be: learn Csound with a good text editor like Vim, and learn how to use Csound on the command line. Embrace Csound as a text-based modular synthesizer and not a programming language (cuz it ain't one!). Avoid slapping on GUI elements for a while until you are comfortable with Csound as a text. Finally, in the words of Max Mathews: "composers should be as lazy as possible when writing scores".

Good luck. I am closing this issue and archiving this repository.

**Closed by PaulBatchelor** 2020-06-17 14:04 UTC
